### ISSUE TITLE
80.WMS小程序预约后，云报关的接单界面的司机电话、车型、司机预约的时间未显示。

### ISSUE THREAD

**Issue by fangducheng** [leaderrun-wms/docs#102]
![image](https://user-images.githubusercontent.com/45841931/58164108-c3f54000-7cb7-11e9-9aff-80787d9f7fac.png)

**Comment by fangducheng** [comment]
CBM汇总数据不正确
![1558665454(1)](https://user-images.githubusercontent.com/45841931/58298978-0d58a300-7e10-11e9-9bf1-bbd4ba6bec38.png)

**Comment by jachyn** [comment]
![80](https://user-images.githubusercontent.com/45808739/58390560-5e60d500-8064-11e9-972a-27e6c70781b2.png)

**Comment by jachyn** [comment]
![80](https://user-images.githubusercontent.com/45808739/58390933-36727100-8066-11e9-9821-db5aef7368d2.png)

**Comment by jachyn** [comment]
Finish
