### ISSUE TITLE
104.KN EDI事项

### ISSUE THREAD

**Issue by ZhouZhiji** [leaderrun-wms/docs#128]
1.需要在货代SO管理界面增加“客户”字段；
2.增加“客户”的查询条件功能；
3.对于有EDI传输的SO号码，在录入ASN时，需判断当前箱数+所有已保存的箱数（作废的ASN不计）是否等于货代SO管理里对应SO的箱数，如果大于（>)，则提示“货代BOOKING SO箱数不够，请联系货代。”，如果小于等于（<=)，则允许录入。

**Comment by yzyzyjm** [comment]
已处理

**Comment by kmtong** [comment]
![image](https://user-images.githubusercontent.com/526674/62018696-5b15d100-b1ee-11e9-9358-122813a0ba57.png)
这需要如何处理吗?
@ZhouZhiji
