### ISSUE TITLE
141.KN EDI判断条件修改

### ISSUE THREAD

**Issue by jachyn** [leaderrun-wms/docs#166]
[KN EDI子客户（收货方）判断汇总-云报关-20191113v1.4.xlsx](https://github.com/leaderrun-wms/docs/files/3840554/KN.EDI.-.-20191113v1.4.xlsx)

[XML.zip](https://github.com/leaderrun-wms/docs/files/3840558/XML.zip)

**Comment by ZhouZhiji** [comment]
因KN提供的资料问题，暂停进行
