### ISSUE TITLE
前台系统设备确认

### ISSUE THREAD

**Issue by kmtong** [leaderrun-wms/docs#22]
请确认前台电脑是否用双屏幕设备，一个来展示给司机看的账单明细。

**Comment by ZhouZhiji** [comment]
唐总，我是想做成线上缴费的，主要的目的是要撤消我现场收费人员，让司机自助交费。我明天下午我会招商银行的开会，会涉及到这一部分的东西，如果有进一步的情况，我反馈在这里。

**Comment by sonboo** [comment]
顶楼上~

**Comment by kmtong** [comment]
如果想在网页上使用微信功能（扫一扫，付款等），得先处理

1. 公众号申请（为了微信网页 JSAPI 功能，并需要绑定网站地址）
2. 网站备案（为了80/443端口的开通）

**Comment by kmtong** [comment]
小票打印机：

* EPSON TM-U220
