### ISSUE TITLE
改包装处理流程

### ISSUE THREAD

**Issue by kmtong** [leaderrun-wms/docs#24]
* 当一个货物被拆开成几个Item，或组成另一个Item的时候，有没有涉及相关人员的操作流程？
* 涉及什么部门的操作？
* 怎样协调？

**Comment by ZhouZhiji** [comment]
唐总，当一个货物被拆开成几个Item，或组成另一个Item的时候，WMS会有发个消息给CMS，让CMS需要重新把关务库存数据和新产生的ITEM做关联，这个操作对于CMS来说，只涉及关务部门。
至于协调，这个做一个改包装的作业任务给关务部门就行。
