### ISSUE TITLE
跨单混装场景

### ISSUE THREAD

**Issue by kmtong** [leaderrun-wms/docs#25]
一车多单情况，一张落货纸，多个ASN号：

1. 合并清单
2. 报关单依旧

具体操作场景？

1. 判断点：在哪里判断是跨单混装
2. 如何操作？合并多份ASN，再传到WMS？还是？

**Comment by kmtong** [comment]
处理方案：

1. 支持一份ASN，录入一份清单，多份报关单；由一家工厂录完。避免跨单导致逻辑校验的问题
2. 工厂在发车前，先进行预约到仓，预约成功后，取一个**预约编号**，用这个**预约编号**交仓
    * 一单一车：选好一份ASN单后，录入一台车辆信息
    * 一单多车：选好一份ASN单后，录入多车信息
    * 一车多单：选好多份ASN单后，再录入一台车辆信息
    * 多单多车：选好多份ASN单后，录入多车信息

**Comment by jachyn** [comment]
Finish
