### ISSUE TITLE
前台接单录入车牌车型等信息，如何反馈给WMS？

### ISSUE THREAD

**Issue by kmtong** [leaderrun-wms/docs#33]
接单界面让操作员录入关于这一单的车牌车型等信息，就算司机之前在司机端录入了，都可以在接单这里改动成为最终的数据。问题是这些数据现在没有接口返回WMS，让WMS重新计费计算

**Comment by ZhouZhiji** [comment]
如果前台更改车型信息，属于信息有更新，这个信息涉及到收费，需要CMS重新推送数据给WMS做重新收费就可以了，不需要重新增加接口。
