### ISSUE TITLE
混装货物的每箱数量（箱规）或每板数量（板规）的校验规则

### ISSUE THREAD

**Issue by ZhouZhiji** [leaderrun-wms/docs#37]
校验规则如下：
清单模版的每箱数量（箱规）或每板数量（板规）是必填的，按照以下方式校验：
1.混箱货物体积计算标识为CTN的，每箱数量（箱规）必填，校验对应行的PCS=对应行的每箱数量（箱规）*同一个混装编号的箱数和
2.1.混箱货物体积计算标识为PLT的，每每板数量（板规）是必填，校验对应行的PCS=对应行的每板数量（板规）*同一个混装编号的板数和

**Comment by kmtong** [comment]
先确认一下改动：

1. 1.0增加混板标识字段
2. 增加2.0校验规则

**Comment by kmtong** [comment]
@ZhouZhiji 最好可以给一个测试数据，和预期结果。

**Comment by ZhouZhiji** [comment]
1.确认增加混板标识字段
2.校验规则不要增加到现在使用的ASN2.0上面，直接放在新的系统里就可以。
3.数据样例：
![image](https://user-images.githubusercontent.com/45655254/53236916-63626100-36d0-11e9-9f94-639b04b26b7c.png)

**Comment by jachyn** [comment]
Finish
