### ISSUE TITLE
审核界面显示出收货方代码，名称，付款方代码名称

### ISSUE THREAD

**Issue by ZhouZhiji** [leaderrun-wms/docs#43]
工厂填制ASN时根据SO识别属于哪个货代或补充，审核界面显示出收货方代码，名称，付款方代码名称。审核组可直接区分属于谁负责审核。

**Comment by yzyzyjm** [comment]
调用1.0接口

**Comment by yzyzyjm** [comment]
因客户数据来源ASN1.0、唯智。以唯智数据为标准，调用1.0时，so识别出客户数据，但唯智没有这个客户数据，则不预填

**Comment by jachyn** [comment]
finish
