### ISSUE TITLE
到仓时间精确到分钟

### ISSUE THREAD

**Issue by ZhouZhiji** [leaderrun-wms/docs#45]

**Comment by yzyzyjm** [comment]
接单页面
1. 预约到仓时间、实际到仓时间放到一块显示

**Comment by yzyzyjm** [comment]
接单页面
* 预约到仓时间、实际到仓时间放到一块显示

**Comment by ZhouZhiji** [comment]
![image](https://user-images.githubusercontent.com/45655254/53390247-8725ef80-39cd-11e9-934f-66f3bd1cc21a.png)
要把这个框的小时、分钟显示出来。

**Comment by ZhouZhiji** [comment]
完成
