### ISSUE TITLE
有关多人同时选定一份单证进行处理的问题

### ISSUE THREAD

**Issue by ZhouZhiji** [leaderrun-wms/docs#49]
审核单证时如有同事点击这份单，显示操作人名，其他人员操作不了这份单，可设置管理员权限，特殊情况管理员可审核这份单

**Comment by qingminzou** [comment]
@see https://github.com/leaderrun-wms/docs/issues/49

**Comment by kmtong** [comment]
改动方案：在审单过程中，增加处理单的审核状态

在审核员点开看一份单的时候，立即改掉单的状态为审核中 (注意不是相同一个ASN状态字段)，并记录审核人。避免一种情况是多人审核同一分单浪费人力。

如果另一个人进去了这份审核中的单，需要提示他某某正在审核中，是否继续？类似提示

主要为了避免多人同时操作时候的协调问题。

效果：

**Comment by ZhouZhiji** [comment]
完成
