### ISSUE TITLE
保税区离境口岸错误

### ISSUE THREAD

**Issue by ZhouZhiji** [leaderrun-wms/docs#52]
保税区离境口岸为深圳盐田综合保税区（代码5352）

**Comment by qingminzou** [comment]
是中通仓吗 ？ 请补充详细，没有明白问题在哪里

**Comment by ZhouZhiji** [comment]
经了解，昨天是因为报关单界面的“离境口岸”字段无法选择导致这一问题，今天测试是可以选择的，放弃问题。
