### ISSUE TITLE
接单界面，司机电话和车牌必填

### ISSUE THREAD

**Issue by ZhouZhiji** [leaderrun-wms/docs#55]
增加必填

**Comment by yzyzyjm** [comment]
车牌号校验大于等于5位即可

**Comment by ZhouZhiji** [comment]
1.接单界面虽然已经有校验司机信息必填，但清单数据比较多，接单按钮处于下方，点接单按钮时，没有任何提示给操作人员，需要增加弹窗提示司机信息为空，需要填写的字样。
2.建议将按钮从下方改成在页面上方，节省滚动业面的时间。
![image](https://user-images.githubusercontent.com/45655254/53789491-76dabb00-3f5f-11e9-9765-0bfc7c6ca4dc.png)
