### ISSUE TITLE
SO识别模板：未识别到输入的SO对应的模板，系统没有提示及指引。

### ISSUE THREAD

**Issue by ZhouZhiji** [leaderrun-wms/docs#58]
增加“识别到对应模板，请手工选择模板”的提示。

**Comment by ZhouZhiji** [comment]
重新说明此问题：是需要在“SO识别模板”界面增加提示功能，当输入的SO未识别到对应的模板，提示“未识别到对应模板，请更换SO号或手动选择模板。”

**Comment by jachyn** [comment]
<img width="842" alt="a" src="https://user-images.githubusercontent.com/45808739/57285294-7c7e8980-70e5-11e9-9f2d-91d3de00bfa0.png">

**Comment by jachyn** [comment]
Finish
