### ISSUE TITLE
接单后，数据下发给唯智系统的状态问题

### ISSUE THREAD

**Issue by ZhouZhiji** [leaderrun-wms/docs#63]
建议在入库接口增加状态字段，接单后下发指令给唯智系统使用订单生效。
整个入库大致按下图所示：
![image](https://user-images.githubusercontent.com/45655254/53621090-4ed21b80-3c30-11e9-911c-eb7bc8fd1a3b.png)

**Comment by yzyzyjm** [comment]
已解决

**Comment by jachyn** [comment]
Finish
