### ISSUE TITLE
收费接口改动，对应的前端界面改动

### ISSUE THREAD

**Issue by yzyzyjm** [leaderrun-wms/docs#84]
参加收费接口文档链接 https://github.com/leaderrun-wms/docs/blob/master/Receivable.md
1. 如status为1，按现有操作进行
2. 如status为2，收费方式增加月结，费用、打印小票均显示零，点击支付，反馈收费确认给唯智
3. 如status为3，前端显示空白

**Comment by ZhouZhiji** [comment]
完成
